name:               "Henrique Max"
description:        "This is a blog about me and professions expericences"

url:                ""
author:             "Henrique Max"
email:              "rickmaxg3@hotmail.com"
gravatar_hash:      "15390d57ab160cc93935c5e9f68b1b31"
twitter:            "Rique_Max"
email:              "rickmaxg3@hotmail.com"
github:             "rickmax"
pinterest:          ""
linkedin:           "henrique-max-321040a3"
facebook:           "henrique.max.73"

disqus_shortname:   "Henrique"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate